### PR TITLE
added option to keep original file extension

### PR DESCRIPTION
**Pull request by ctrl-f5**
option defaults to false to keep things running the way they were without the need for any extra config.

resolves issue #3

### CODE REVIEW

**Comment by mt80** [comment]
Hello. Could you create a pull request to merge these changes into the new branch 3.0? We will put in there all symfony 3 compatible code.

**Comment by ctrl-f5** [comment]
3.0? there isn't a 2.0 version?

anyway, in the meantime I already forked this repo, merged all the other PR's that were hanging here, and updated master with symfony3 compatibility, as a 2.0 branch alias: https://github.com/ctrl-f5/FileManager

feel free to merge this back into this repo.

**Comment by mt80** [comment]
we named it 3.0 because it is for symfony 3

**Comment by mt80** [comment]
we added some of your changes in our 3.0 branch. Thank you for the contribution

**Pull request closed without merging**
